# Generated by Django 5.2 on 2025-05-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_expense_user_income_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#808080', help_text='Введіть HEX-код кольору (наприклад, #FF5733)', max_length=7, verbose_name='Колір для діаграм'),
        ),
    ]
