# Generated by Django 5.2 on 2025-04-25 17:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата запису')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок/Тема')),
                ('content', models.TextField(verbose_name='Зміст нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Нотатка',
                'verbose_name_plural': 'Нотатки',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notes_photos/%Y/%m/%d/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Підпис до фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='notes.note', verbose_name='Нотатка')),
            ],
            options={
                'verbose_name': 'Фото до нотатки',
                'verbose_name_plural': 'Фото до нотаток',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
